name: Supabase Backup

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 2 * * *"

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Postgres client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Pick connection (direct → pooler)
        id: pickuri
        env:
          DIRECT: ${{ secrets.SUPABASE_DB_URL }}
          POOLER: ${{ secrets.SUPABASE_DB_URL_POOLER }}
        run: |
          set -e
          if psql "$DIRECT" -c '\q' >/dev/null 2>&1; then
            echo "pguri=$DIRECT" >> "$GITHUB_OUTPUT"
            echo "Using direct connection."
          elif psql "$POOLER" -c '\q' >/dev/null 2>&1; then
            echo "pguri=$POOLER" >> "$GITHUB_OUTPUT"
            echo "Using session pooler."
          else
            echo "Failed to connect with both URIs."
            exit 1
          fi

      - name: pg_dump
        env:
          PGURI: ${{ steps.pickuri.outputs.pguri }}
        run: |
          set -e
          DATE=$(date +%F)
          FILE="backup_${DATE}.dump"
          pg_dump "$PGURI" --format=custom --no-owner --no-privileges --verbose --file="$FILE"
          echo "FILE=$FILE" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-backup
          path: ${{ env.FILE }}
          retention-days: 7
